name       : nats
version    : 1.1.1
release    : 1
source     :
    - http://hackage.haskell.org/package/nats-1.1.1/nats-1.1.1.tar.gz : 131d1b4857cd1c0699ef60aeb41af923ee3e0ecd26ed1324c067d993bc17d4cd
license    : BSD-3-Clause
component  : programming.haskell
summary    : Natural numbers
description: |
    Natural number support for Haskell
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-hashable
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
